import type { Transaction, CategoryBudget } from '../types/finance';

const getRelativeDate = (daysAgo: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
};

export const INITIAL_BUDGETS: CategoryBudget[] = [
  { category: 'Alimentation & Courses', monthlyLimit: 400 },
  { category: 'Logement & Loyer', monthlyLimit: 850 },
  { category: 'Transports', monthlyLimit: 150 },
  { category: 'Loisirs & Sorties', monthlyLimit: 250 },
  { category: 'Factures & Abonnements', monthlyLimit: 200 },
  { category: 'Shopping & Achats', monthlyLimit: 200 },
  { category: 'Santé', monthlyLimit: 100 },
  { category: 'Éducation', monthlyLimit: 120 },
  { category: 'Autre Dépense', monthlyLimit: 100 },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    title: 'Salaire Mensuel',
    amount: 3200,
    category: 'Salaire',
    date: getRelativeDate(25),
    notes: 'Virement de l’employeur Tech Corp',
  },
  {
    id: 'tx-2',
    type: 'expense',
    title: 'Loyer du mois',
    amount: 850,
    category: 'Logement & Loyer',
    date: getRelativeDate(24),
    notes: 'Prélèvement automatique bailleur',
  },
  {
    id: 'tx-3',
    type: 'income',
    title: 'Mission Freelance React',
    amount: 750,
    category: 'Freelance',
    date: getRelativeDate(20),
    notes: 'Projet Dashboard Client X',
  },
  {
    id: 'tx-4',
    type: 'expense',
    title: 'Courses Carrefour',
    amount: 145.5,
    category: 'Alimentation & Courses',
    date: getRelativeDate(18),
    notes: 'Achats alimentaires de la semaine',
  },
  {
    id: 'tx-5',
    type: 'expense',
    title: 'Abonnement Fibre & Mobile',
    amount: 59.9,
    category: 'Factures & Abonnements',
    date: getRelativeDate(17),
    notes: 'Orange Telecom',
  },
  {
    id: 'tx-6',
    type: 'expense',
    title: 'Passe Navigo / Carburant',
    amount: 84.2,
    category: 'Transports',
    date: getRelativeDate(15),
    notes: 'Transport mensuel',
  },
  {
    id: 'tx-7',
    type: 'expense',
    title: 'Restaurant & Bar Concert',
    amount: 110.0,
    category: 'Loisirs & Sorties',
    date: getRelativeDate(12),
    notes: 'Soirée entre amis',
  },
  {
    id: 'tx-8',
    type: 'expense',
    title: 'Courses Biocoop',
    amount: 135.0,
    category: 'Alimentation & Courses',
    date: getRelativeDate(10),
    notes: 'Produits frais & bio',
  },
  {
    id: 'tx-9',
    type: 'expense',
    title: 'Weekend Escape Hôtel',
    amount: 210.0,
    category: 'Loisirs & Sorties',
    date: getRelativeDate(7),
    notes: 'Réservation séjour weekend',
  },
  {
    id: 'tx-10',
    type: 'expense',
    title: 'Abonnement Salle de Sport & Streaming',
    amount: 89.0,
    category: 'Factures & Abonnements',
    date: getRelativeDate(5),
    notes: 'Fitness Park + Netflix + Spotify',
  },
  {
    id: 'tx-11',
    type: 'expense',
    title: 'Supermarché Express',
    amount: 105.0,
    category: 'Alimentation & Courses',
    date: getRelativeDate(3),
    notes: 'Réapprovisionnement cuisine',
  },
  {
    id: 'tx-12',
    type: 'income',
    title: 'Vente Matériel Occasion',
    amount: 160.0,
    category: 'Vente',
    date: getRelativeDate(2),
    notes: 'Revente écran informatique',
  },
  {
    id: 'tx-13',
    type: 'expense',
    title: 'Nouvelles Baskets & Vêtements',
    amount: 175.0,
    category: 'Shopping & Achats',
    date: getRelativeDate(1),
    notes: 'Solde vêtements d’été',
  },
];
